import  bcrypt   from 'bcryptjs';
const data = {
  users: [{

    name: 'Praveen',
    email: 'admin@example.com',
    password: bcrypt.hashSync('1234556'),
    isAdmin: true,
  },
  {

    name: 'sai',
    email: 'users@example.com',
    password: bcrypt.hashSync('1234556'),
    isAdmin: false,
    },],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: '70',
      brand: 'mufti',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'slimfit Shirt',
      slug: 'slimfit-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: '100',
      brand: 'H&M',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'jeen Pant',
      slug:'jeen-pant',
      category: 'jeen',
      image: '/images/pants1.jpg',
      price: '70',
      brand: 'mufti',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'pant',
      slug: 'pant',
      category: 'slimfit',
      image: '/images/pants2.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'pant-jinu',
      slug: 'pant-jinu',
      category: 'slimfit',
      image: '/images/pants3.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInstocks: 20,
      description: 'A popular shirt',
    },

  ],
};
export default data;
